CLUBS = {
            'Countermeasure': 'Countermeasure Council',
            'GourmetClub': 'Gourmet Research Club',
            'RemedialClass': 'Supplemental Classes Club',
            'SisterHood': 'Sisterhood',
            'Kohshinjo68': 'Problem Solver 68',
            'CleanNClearing': 'Cleaning & Clearing',
            'Shugyobu': 'Inner Discipline Club',
            'MatsuriOffice': 'Festival Organization Committee',
            'Endanbou': 'Chinese alchemy study group',
            'Class227': 'Class No. 227',
            'HoukagoDessert': 'After School Sweets Club',
            'GameDev': 'Game Development Club',
            'Veritas': 'Veritas',
            'Engineer': 'Engineering Club',
            'KnightsHospitaller': 'Rescue Knights',
            'FoodService': 'School Lunch Club',
            'PandemoniumSociety': 'Pandemonium Society',
            'RabbitPlatoon': 'RABBIT Platoon',
            'Emergentology': 'Emergency Medicine Department',
            'RedwinterSecretary': 'Red Winter Secretariat',
            'Fuuki': 'Disciplinary Committee',
            'NinpoKenkyubu': 'Ninjutsu Research Department',
            'anzenkyoku': 'Community Safety Bureau',
            'Justice': 'Justice Task Force',
            'TrinityVigilance': 'Vigilante Corps',
            'Onmyobu': 'Yin-Yang Club',
            'BookClub': 'Library Committee',
            'Meihuayuan': 'Plum Blossom Garden',
            'TrainingClub': 'Training Club',
            'SPTF': 'Supernatural Phenomenon Task Force',
            'TheSeminar': 'Seminar',
            'AriusSqud': 'Arius Squad',
            'PublicPeaceBureau':'Public Peace Bureau',
            'HotSpringsDepartment':'Hot Springs Development Department',
            'TeaParty':'Tea Party',
            'Genryumon': 'Genryumon',
            'BlackTortoisePromenade': 'Black Tortoise Promenade',
            'LaborParty': 'Labor Party',
            'KnowledgeLiberationFront': 'Knowledge Liberation Front',
            'Hyakkayouran': 'Hyakkaryouran',
            'EmptyClub': 'no club'
}
