CLUBS = {
            'Countermeasure': 'Foreclosure Task Force',
            'GourmetClub': 'Gourmet Research Society',
            'RemedialClass': 'Make-Up Work Club', #'Supplemental Lessons Club',
            'SisterHood': 'The Sisterhood',
            'Kohshinjo68': 'Problem Solver 68',
            'CleanNClearing': 'Cleaning & Clearing',
            'Shugyobu': 'Inner Discipline Club',
            'MatsuriOffice': 'Festival Organization Committee',
            'Endanbou': 'Chinese alchemy study group',
            'Class227': 'Class No. 227',
            'HoukagoDessert': 'After-School Sweets Club',
            'GameDev': 'Game Development Club',
            'Veritas': 'Veritas',
            'Engineer': 'Engineering Department',
            'KnightsHospitaller': 'Rescue Knights',
            'FoodService': 'School Lunch Club',
            'PandemoniumSociety': 'Pandemonium Society',
            'RabbitPlatoon': 'RABBIT Platoon',
            'Emergentology': 'Emergency Medicine Department',
            'RedwinterSecretary': 'Red Winter Secretariat',
            'Fuuki': 'Prefect Team',
            'NinpoKenkyubu': 'Ninjutsu Research Department',
            'anzenkyoku': 'Public Safety Bureau',
            'Justice': 'Justice Task Force',
            'TrinityVigilance': 'Trinity\'s Vigilante Crew',
            'Onmyobu': 'Yin-Yang Club',
            'BookClub': 'Library Committee',
            'Meihuayuan': 'Plum Blossom Garden',
            'TrainingClub': 'Athletics Training Club',
            'SPTF': 'Super Phenomenon Task Force',
            'TheSeminar': 'Seminar',
            'AriusSqud': 'Arius Squad',
            'PublicPeaceBureau':'Public Peace Bureau',
            'HotSpringsDepartment':'Hot Springs Department',
            'TeaParty':'Tea Party',
            'Genryumon': 'Genryumon',
            'BlackTortoisePromenade': 'Black Tortoise Promenade',
            'LaborParty': 'Labor Party',
            'KnowledgeLiberationFront': 'Knowledge Liberation Front',
            'Hyakkayouran': 'Hyakkaryouran',
            'ShinySparkleSociety': 'Shiny Sparkle Society',
            'AbydosStudentCouncil': 'Abydos Student Council',
            'CentralControlCenter': 'CCC',
            'FreightLogisticsDepartment': 'Freight Logistics Department',
            'OccultClub': 'Occult Research Society',
            'PrefectBrigade': 'Prefect Brigade',
            'EmptyClub': 'no club'
}

SCHOOLS = {
    'RedWinter': 'Red Winter',
    'WildHunt': 'Wildhunt'
}
